/*Copyright (c) 2016-2017 vcstest1.com All Rights Reserved.
 This software is the confidential and proprietary information of vcstest1.com You shall not disclose such Confidential Information and shall use it only in accordance
 with the terms of the source code license agreement you entered into with vcstest1.com*/

package com.testsoapshare.adventureworks2014.service;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/

import java.util.HashMap;
import java.util.List;
import java.util.Map;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.beans.factory.annotation.Qualifier;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

import com.wavemaker.runtime.data.dao.procedure.WMProcedureExecutor;

import com.testsoapshare.adventureworks2014.models.procedure.*;

@Service
public class AdventureWorks2014ProcedureExecutorServiceImpl_V1 implements AdventureWorks2014ProcedureExecutorService_V1 {

    private static final Logger LOGGER = LoggerFactory.getLogger(AdventureWorks2014ProcedureExecutorServiceImpl.class);

    @Autowired
    @Qualifier("AdventureWorks2014WMProcedureExecutor")
    private WMProcedureExecutor procedureExecutor;

    public List<Object> executeProc1(Integer id) {
        Map params = new HashMap(1);

        params.put("Id", id);

        return procedureExecutor.executeNamedProcedure("proc1", params);

    }

}


