/*Copyright (c) 2016-2017 vcstest1.com All Rights Reserved.
 This software is the confidential and proprietary information of vcstest1.com You shall not disclose such Confidential Information and shall use it only in accordance
 with the terms of the source code license agreement you entered into with vcstest1.com*/
package com.testsoapshare.adventureworks2014.models.procedure;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/


import java.io.Serializable;
import java.sql.Timestamp;
import java.util.List;
import java.util.Objects;

import com.fasterxml.jackson.annotation.JsonProperty;
import com.wavemaker.runtime.data.annotations.ColumnAlias;

public class Proc1ResponseContent implements Serializable {


    @JsonProperty("DepartmentID")
    @ColumnAlias("DepartmentID")
    private Short departmentId;

    @JsonProperty("Name")
    @ColumnAlias("Name")
    private String name;

    @JsonProperty("GroupName")
    @ColumnAlias("GroupName")
    private String groupName;

    @JsonProperty("ModifiedDate")
    @ColumnAlias("ModifiedDate")
    private Timestamp modifiedDate;

    public Short getDepartmentId() {
        return this.departmentId;
    }

    public void setDepartmentId(Short departmentId) {
        this.departmentId = departmentId;
    }

    public String getName() {
        return this.name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getGroupName() {
        return this.groupName;
    }

    public void setGroupName(String groupName) {
        this.groupName = groupName;
    }

    public Timestamp getModifiedDate() {
        return this.modifiedDate;
    }

    public void setModifiedDate(Timestamp modifiedDate) {
        this.modifiedDate = modifiedDate;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (!(o instanceof Proc1ResponseContent)) return false;
        final Proc1ResponseContent proc1responseContent = (Proc1ResponseContent) o;
        return Objects.equals(getDepartmentId(), proc1responseContent.getDepartmentId()) &&
                Objects.equals(getName(), proc1responseContent.getName()) &&
                Objects.equals(getGroupName(), proc1responseContent.getGroupName()) &&
                Objects.equals(getModifiedDate(), proc1responseContent.getModifiedDate());
    }

    @Override
    public int hashCode() {
        return Objects.hash(getDepartmentId(),
                getName(),
                getGroupName(),
                getModifiedDate());
    }
}
